import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        /** Account / commerce UI — mirrors globals.css `--ds-*` */
        ds: {
          page: "var(--ds-page-bg)",
          surface: "var(--ds-surface)",
          surfaceMuted: "var(--ds-surface-muted)",
          surfaceSubtle: "var(--ds-surface-subtle)",
          border: "var(--ds-border-default)",
          borderMuted: "var(--ds-border-muted)",
          borderStrong: "var(--ds-border-strong)",
          heading: "var(--ds-text-heading)",
          body: "var(--ds-text-body)",
          textMuted: "var(--ds-text-muted)",
          textSubtle: "var(--ds-text-subtle)",
          focus: "var(--ds-focus-ring)",
        },
        edu: {
          page: "#F4F1FF",
          card: "#FFFFFF",
          primary: "#6C63FF",
          cta: "#FF6B73",
          ctaHover: "#FF5964",
          text: "#1F2937",
          muted: "#6B7280",
          border: "#E5E7EB",
          success: "#22C55E",
          warning: "#F59E0B",
          error: "#EF4444",
        },
        intent: {
          flow: "#FF6B73",
          action: "#6C63FF",
          neutral: "#FFFFFF",
          danger: "#EF4444",
        },
        status: {
          draftBg: "#F3F4F6",
          draftText: "#4B5563",
          pendingReviewBg: "#FEF3C7",
          pendingReviewText: "#B45309",
          publishedBg: "#ECFDF5",
          publishedText: "#047857",
          unpublishedBg: "#F3F4F6",
          unpublishedText: "#4B5563",
          pendingPaymentBg: "#FFE4E6",
          pendingPaymentText: "#FF6B73",
          approvedBg: "#ECFDF5",
          approvedText: "#047857",
          rejectedBg: "#FEE2E2",
          rejectedText: "#B91C1C",
          reviewedBg: "#EDE9FE",
          reviewedText: "#6C63FF",
        },
        feedback: {
          loadingText: "#6B7280",
          loadingSpinnerPrimary: "#6C63FF",
          loadingSpinnerTrack: "#DDEBFA",
          emptyIconBg: "#EDE9FE",
          emptyTitle: "#1F2937",
          emptyDescription: "#6B7280",
          emptyAction: "#6C63FF",
          errorBg: "#FEF2F2",
          errorBorder: "#FECACA",
          errorText: "#B91C1C",
        },
      },
      boxShadow: {
        "ds-card": "var(--ds-shadow-card)",
        "ds-card-soft": "var(--ds-shadow-card-soft)",
        "ds-card-hover": "var(--ds-shadow-card-hover)",
        edu: "0 10px 40px rgba(15, 23, 42, 0.06)",
        "edu-lg": "0 16px 48px rgba(108, 99, 255, 0.12)",
        "card-elevated": "0 18px 60px rgba(15, 23, 42, 0.10)",
        "card-default": "0 10px 40px rgba(15, 23, 42, 0.06)",
        "button-flow": "0 8px 24px rgba(255, 107, 115, 0.28)",
        "button-action": "0 6px 20px rgba(108, 99, 255, 0.22)",
      },
      maxWidth: {
        mobile: "390px",
        narrow: "768px",
        normal: "1024px",
        wide: "1280px",
      },
      ringOffsetColor: {
        ds: "var(--ds-page-bg)",
      },
      spacing: {
        "layout-sidebar": "240px",
        "page-mobile": "16px",
        "page-tablet": "24px",
        "page-desktop": "32px",
        "section-sm": "16px",
        "section-md": "24px",
        "section-lg": "32px",
        "section-xl": "48px",
      },
      borderRadius: {
        "ds-card": "var(--ds-radius-card)",
        "card-elevated": "32px",
        "card-default": "28px",
        "card-flat": "24px",
      },
      fontSize: {
        h1: ["2rem", { lineHeight: "2.5rem", fontWeight: "700" }],
        h2: ["1.5rem", { lineHeight: "2rem", fontWeight: "700" }],
        h3: ["1.25rem", { lineHeight: "1.75rem", fontWeight: "700" }],
        title: ["1rem", { lineHeight: "1.5rem", fontWeight: "600" }],
        body: ["0.875rem", { lineHeight: "1.375rem", fontWeight: "400" }],
        meta: ["0.75rem", { lineHeight: "1.125rem", fontWeight: "500" }],
        caption: ["0.6875rem", { lineHeight: "1rem", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
