export const designTokens = {
  colors: {
    primary: "#6c63ff",
    primaryHover: "#5b52ee",
    cta: "#ff6b73",
    ctaHover: "#ff5964",
    action: "#6c63ff",
    neutral: "#ffffff",
    success: "#16a34a",
    warning: "#d97706",
    danger: "#ef4444",
    info: "#6c63ff",
    bg: {
      page: "#f4f1ff",
      surface: "#ffffff",
      muted: "#faf8ff",
      error: "#fef2f2",
    },
    text: {
      primary: "#1f2937",
      secondary: "#6b7280",
      muted: "#9ca3af",
      inverse: "#ffffff",
      danger: "#b91c1c",
    },
    border: {
      default: "#e5e7eb",
      strong: "#cbd5e1",
      danger: "#fecaca",
    },
    status: {
      draft: { bg: "#f3f4f6", text: "#4b5563" },
      pendingReview: { bg: "#fef3c7", text: "#b45309" },
      published: { bg: "#ecfdf5", text: "#047857" },
      unpublished: { bg: "#f3f4f6", text: "#4b5563" },
      pendingPayment: { bg: "#ffe4e6", text: "#ff6b73" },
      approved: { bg: "#ecfdf5", text: "#047857" },
      rejected: { bg: "#fee2e2", text: "#b91c1c" },
      reviewed: { bg: "#ede9fe", text: "#6c63ff" },
    },
    feedback: {
      loadingText: "#6b7280",
      spinnerPrimary: "#6c63ff",
      spinnerTrack: "#ddebfa",
      emptyIconBg: "#ede9fe",
      emptyTitle: "#1f2937",
      emptyDescription: "#6b7280",
      emptyAction: "#6c63ff",
      errorBg: "#fef2f2",
      errorBorder: "#fecaca",
      errorText: "#b91c1c",
    },
  },
  fontSizes: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 20,
    xl: 28,
  },
  lineHeights: {
    xs: 16,
    sm: 20,
    md: 24,
    lg: 28,
    xl: 36,
  },
  typography: {
    heading: {
      h1: { size: 28, lineHeight: 36 },
      h2: { size: 20, lineHeight: 28 },
      h3: { size: 16, lineHeight: 24 },
    },
    body: {
      regular: { size: 16, lineHeight: 24 },
      small: { size: 14, lineHeight: 20 },
      caption: { size: 12, lineHeight: 16 },
    },
  },
  space: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  },
  radius: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    cardFlat: 24,
    cardDefault: 28,
    cardElevated: 32,
  },
  shadows: {
    sm: {
      shadowColor: "#0f172a",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 3,
      elevation: 1,
    },
    md: {
      shadowColor: "#0f172a",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 2,
    },
    cardElevated: {
      shadowColor: "#0f172a",
      shadowOffset: { width: 0, height: 18 },
      shadowOpacity: 0.1,
      shadowRadius: 30,
      elevation: 6,
    },
    cardDefault: {
      shadowColor: "#0f172a",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.06,
      shadowRadius: 20,
      elevation: 3,
    },
  },
} as const;

export type DesignTokens = typeof designTokens;
